version = 0.1

[default.build.parameters]
use_container = true

[default.deploy.parameters]
stack_name = "api-medic-demo"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
confirm_changeset = false
fail_on_empty_changeset = false
