/* eslint-disable */
/**
 * AUTO-GENERATED by 'make types' from Pydantic models in src/api_medic/core/models.py.
 * Do not edit by hand. Run 'make types' to regenerate.
 */
/**
 * The single artifact produced by every api-medic surface.
 *
 * A Report from the CLI, the local web UI, the hosted demo, or the browser
 * extension is byte-identical given the same input. Don't break that.
 */
export interface Report {
    findings?: Finding[];
    id?:       string;
    request:   RequestSummary;
    /**
     * Null when the request never completed (DNS failure, connect timeout, etc).
     */
    response?:       ResponseSummary | null;
    schema_version?: string;
    source:          Source;
    timestamp?:      string;
    timing:          TimingBreakdown;
}

/**
 * A single diagnostic finding produced by one check.
 *
 * Findings have three layers (matching the UI design):
 * - `title`: plain-language headline for non-technical readers
 * - `evidence`: structured raw data for technical readers
 * - `suggested_fix`: actionable next step
 */
export interface Finding {
    /**
     * Structured raw data for the technical reader. Optional.
     */
    evidence?: { [key: string]: any } | null;
    /**
     * Plain-language body.
     */
    explanation: string;
    /**
     * Stable, namespaced check identifier (e.g. 'auth.jwt.expired', 'network.dns.no_records').
     */
    id:       string;
    severity: Severity;
    /**
     * Action to take. Optional — not every finding has a clear fix.
     */
    suggested_fix?: null | string;
    /**
     * Plain-language headline.
     */
    title: string;
}

export type Severity = "info" | "warning" | "critical";

/**
 * Captured snapshot of the request that was sent (or would have been sent).
 */
export interface RequestSummary {
    /**
     * First ~500 chars, or null if binary.
     */
    body_preview?:   null | string;
    body_size_bytes: number;
    headers?:        { [key: string]: string };
    /**
     * HTTP method, uppercase.
     */
    method: string;
    url:    string;
}

/**
 * Captured snapshot of the response received.
 */
export interface ResponseSummary {
    body_preview?:   null | string;
    body_size_bytes: number;
    headers?:        { [key: string]: string };
    /**
     * Negotiated protocol, e.g. 'HTTP/1.1', 'HTTP/2'.
     */
    protocol:    string;
    status_code: number;
    /**
     * e.g. 'OK', 'Unauthorized'.
     */
    status_text: string;
}

export type Source = "live" | "har" | "curl" | "raw" | "extension";

/**
 * Per-phase request timing in milliseconds.
 *
 * Every field is nullable: captured-mode reports (HAR, curl) may not have
 * full per-phase timing data.
 */
export interface TimingBreakdown {
    connect_ms?:  number | null;
    dns_ms?:      number | null;
    download_ms?: number | null;
    tls_ms?:      number | null;
    total_ms?:    number | null;
    ttfb_ms?:     number | null;
}
